# Generated by Django 5.1.4 on 2026-08-09 06:37

import documents.models
import documents.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_content_type_document_size_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=512, storage=documents.storages.get_document_storage, upload_to=documents.models.document_upload_path),
        ),
    ]
